from pathlib import Path

DATA_DIR = Path(r"S:\PROJETOS EM ANDAMENTO\PAINEL DE CONTROLE MTECH\PROGRAMAS\PROJETOS -BACKEND\output")
BACKEND_DIR = DATA_DIR.parent
SQLITE_DB_PATH = BACKEND_DIR / "db.sqlite3"
FORMS_DIR = Path("BASE DE DADOS FORMS")
LOGO_PATH = Path("brand_logo.png")
BACKGROUND_PATH = Path("brand_bg.png")

PRIMARY = "#00a3a3"
PRIMARY_LIGHT = "#7cd4d4"
PRIMARY_DARK = "#0b3a44"
SURFACE = "rgba(12, 41, 47, 0.75)"

DISPLAY_PLANILHA_MAP = {
    "ILHA MADEIRA GRANDE": "LISTA DE PROCESSO ILHA MADEIRA.xlsx",
    "PG + ECONOMIA HIBRIDO": "LISTA DE PROCESSO PG + ECO HIBRIDO LADO MENOR.xlsx",
    "PG LED NEON VERMELHO": "LISTA DE PROCESSO PG LED NEON VERMELHO.xlsx",
    "PG POWERADE": "LISTA DE PROCESSO PDG POWERADE.xlsx",
    "RACK FLEX - 04 BANDEJAS": "LISTA DE PROCESSO RACK FLEX 4 BANDEJAS.xlsx",
    "RACK KAPO ATACADO FDS": "LISTA DE PROCESSO RACK KAPO ATACADO FDS.xlsx",
    "RACK LS+REFPET": "LISTA DE PROCESSO RACK LS+REFPET.xlsx",
    "RACK MEIO PALLET COCA": "LISTA DE PROCESSO RACK MEIO PALLET COCA.xlsx",
    "RACK MINI ADES": "LISTA DE PROCESSO RACK MINI ADES.xlsx",
    "RACK MINI FLEX - 07 BANDEJAS": "LISTA DE PROCESSO RACK MINI FLEX 7 BANDEJAS.xlsx",
    "RACK PARASITA": "LISTA DE PROCESSO RACK PARASITA.xlsx",
    "RACK SLIM CRYSTAL": "LISTA DE PROCESSO RACK CRYSTAL.xlsx",
}
